### ISSUE TITLE
medication cabinet page loads content for user w/o permission before showing unauthorized message

### ISSUE THREAD

**Issue by dukemike** [interopion/cloudrx-issues#1]
The Medication Cabinet page loads content for user w/o permission before showing the unauthorized message which allows the user to attempt to add a medication.

<img width="890" alt="cloud_rx" src="https://cloud.githubusercontent.com/assets/11562781/15167616/5dcbf670-16f8-11e6-9baa-a8c8c9ec88bc.png">

**Comment by dukemike** [comment]
To replicate, click the refresh button several times quickly.

**Comment by vlad-ignatov** [comment]
Now there is no such page (nor links to it) for developers and no "Add Medication" button for drug viewers
