### ISSUE TITLE
image aspect ratio always "NaN/NaN" and dimensions always 0x0

### ISSUE THREAD

**Issue by dukemike** [interopion/cloudrx-issues#10]
<img width="389" alt="cursor_and_cloud_rx" src="https://cloud.githubusercontent.com/assets/11562781/16429478/fdbc9410-3d44-11e6-8807-2429536acd44.png">

**Comment by dukemike** [comment]
Using Safari on OS X El Capitan.

**Comment by vlad-ignatov** [comment]
This should be fixed now
