### ISSUE TITLE
unable to sign in to CloudRX flasgger Documentation

### ISSUE THREAD

**Issue by dukemike** [interopion/cloudrx-issues#12]
https://cloudrx.medapptech.com/api/apidocs/index.html?url=/api/spec never shows the documentation.

**Comment by vasofilipov** [comment]
There are some issues with Safari, but now it should let you sign in, if you can't focus on the password field you can use tab to switch between the user and password text input.

**Comment by vasofilipov** [comment]
The login form on the API documentation should now work as expected. 
https://cloudrx.medapptech.com/api/apidocs/index.html?url=/api/spec

**Comment by dukemike** [comment]
I'm able to login now.
