### ISSUE TITLE
mymedlist: unable to add meds to regimen

### ISSUE THREAD

**Issue by dukemike** [interopion/cloudrx-issues#14]
I can't add any med to my regimen. I'm using Safari on El Capitan.

[add-med-to-regimen.mov.zip](https://github.com/medapptech/cloudrx-issues/files/343644/add-med-to-regimen.mov.zip)

**Comment by dukemike** [comment]
I think this may be caused by the way I'm using it or an issue with the calendar. I can see things in the month view that aren't in the day or week view.

My user account is `dukemike`.

**Comment by vlad-ignatov** [comment]
This is fixed. Please clear the cache before retrying.
