### ISSUE TITLE
add filter to medication listing for 'medications without photos'

### ISSUE THREAD

**Issue by dukemike** [interopion/cloudrx-issues#6]
Once we have several pages of drugs, knowing which ones need drugs will be become tedious. Adding a filter to exclude medications with photos would allow us to easily identify medications to focus on.

**Comment by vlad-ignatov** [comment]
There are two new filters now. You limit your results to meds with/without image and with/without NDC.
You can also sort by "Updated At" to see the oldest or newest records.
