### ISSUE TITLE
[mymedlist] display manufacturer when adding medicine

### ISSUE THREAD

**Issue by dukemike** [interopion/cloudrx-issues#9]
When adding a medication we need additional information to know which one to pick. I don't know if adding just the manufacturer will be enough, but let's start there.

**Comment by vlad-ignatov** [comment]
This is done. An image, manufacturer and link to detailed description will be shown if available. Please make sure you clear the browser cache to see the changes.
<img width="636" alt="screen shot 2016-11-18 at 2 26 23 pm" src="https://cloud.githubusercontent.com/assets/1119082/20430120/33ee5b1a-ad9b-11e6-91b8-1b931900791f.png">
